name: java-maven-build-workflow
run-name: ${{ github.actor }} is building this project
on:
  push
jobs:
  Sample-build-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is runnig on ${{ runner.os }}"
      - run: echo "Cloning branch ${{ github.ref }} from repo ${{ github.repository }}"
      ## Cloning source code
      - name: Clone Source Code
        uses: actions/checkout@v4
      - run: echo "Repo ${{ github.repository }} cloned to the runner"
