name: java-maven-build-workflow
run-name: ${{ github.actor }} is building this project
on:
  push
jobs:
  Sample-build-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is runnig on ${{ runner.os }}"
      - run: echo "Cloning branch ${{ github.ref }} from repo ${{ github.repository }}"
      ## Cloning source code
      - name: Clone Source Code
        uses: actions/checkout@v4
      - run: echo "Repo ${{ github.repository }} cloned to the runner"      
      ## Setting up java version
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      ## Build app using maven
      - name: Build with Maven
        run: mvn clean package
      - run: echo "Application built successfully"
